---
version: "2"
services:
  slskd:
    image: slskd/slskd
    container_name: slskd
    restart: unless-stopped
    
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
      
    environment:
      SLSKD_REMOTE_CONFIGURATION: "true"
      SLSKD_SLSK_USERNAME: "rufusnu"
      SLSKD_SLSK_PASSWORD: "house32mE"
      SLSKD_SHARED_DIR: "/mnt/ciocanuzfs/_smb/rufusnu/DJ/Music"
      SLSKD_NO_AUTH: "true"
      
    volumes:
      - /home/rufusnu/soulseek-automation/slskd/data:/app