---
version: "2"
services:
  slskd:
    image: slskd/slskd
    container_name: slskd
    restart: unless-stopped
    
    ports:
      - "5030:5030"
      - "5031:5031"
      - "50300:50300"
      
    environment:
      SLSKD_REMOTE_CONFIGURATION: "true"
      SLSKD_SLSK_USERNAME: "[username]"
      SLSKD_SLSK_PASSWORD: "[password]"
      SLSKD_SHARED_DIR: "[Soulseek/Shared/Directory]"
      SLSKD_NO_AUTH: "true"
      
    volumes:
      - ./data:/app  # Change if Needed: directory where slskd creates downloads, incomplete, data and scripts directories

